/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteRegistryFunctionOrgNameTagReader is a Reader for the DeleteRegistryFunctionOrgNameTag structure.
type DeleteRegistryFunctionOrgNameTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRegistryFunctionOrgNameTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRegistryFunctionOrgNameTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRegistryFunctionOrgNameTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteRegistryFunctionOrgNameTagUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRegistryFunctionOrgNameTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRegistryFunctionOrgNameTagInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /registry/function/{org}/{name}/{tag}] DeleteRegistryFunctionOrgNameTag", response, response.Code())
	}
}

// NewDeleteRegistryFunctionOrgNameTagOK creates a DeleteRegistryFunctionOrgNameTagOK with default headers values
func NewDeleteRegistryFunctionOrgNameTagOK() *DeleteRegistryFunctionOrgNameTagOK {
	return &DeleteRegistryFunctionOrgNameTagOK{}
}

/*
DeleteRegistryFunctionOrgNameTagOK describes a response with status code 200, with default header values.

OK
*/
type DeleteRegistryFunctionOrgNameTagOK struct {
	Payload string
}

// IsSuccess returns true when this delete registry function org name tag o k response has a 2xx status code
func (o *DeleteRegistryFunctionOrgNameTagOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete registry function org name tag o k response has a 3xx status code
func (o *DeleteRegistryFunctionOrgNameTagOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete registry function org name tag o k response has a 4xx status code
func (o *DeleteRegistryFunctionOrgNameTagOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete registry function org name tag o k response has a 5xx status code
func (o *DeleteRegistryFunctionOrgNameTagOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete registry function org name tag o k response a status code equal to that given
func (o *DeleteRegistryFunctionOrgNameTagOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete registry function org name tag o k response
func (o *DeleteRegistryFunctionOrgNameTagOK) Code() int {
	return 200
}

func (o *DeleteRegistryFunctionOrgNameTagOK) Error() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagOK  %+v", 200, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagOK) String() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagOK  %+v", 200, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteRegistryFunctionOrgNameTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRegistryFunctionOrgNameTagBadRequest creates a DeleteRegistryFunctionOrgNameTagBadRequest with default headers values
func NewDeleteRegistryFunctionOrgNameTagBadRequest() *DeleteRegistryFunctionOrgNameTagBadRequest {
	return &DeleteRegistryFunctionOrgNameTagBadRequest{}
}

/*
DeleteRegistryFunctionOrgNameTagBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteRegistryFunctionOrgNameTagBadRequest struct {
	Payload string
}

// IsSuccess returns true when this delete registry function org name tag bad request response has a 2xx status code
func (o *DeleteRegistryFunctionOrgNameTagBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete registry function org name tag bad request response has a 3xx status code
func (o *DeleteRegistryFunctionOrgNameTagBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete registry function org name tag bad request response has a 4xx status code
func (o *DeleteRegistryFunctionOrgNameTagBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete registry function org name tag bad request response has a 5xx status code
func (o *DeleteRegistryFunctionOrgNameTagBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete registry function org name tag bad request response a status code equal to that given
func (o *DeleteRegistryFunctionOrgNameTagBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete registry function org name tag bad request response
func (o *DeleteRegistryFunctionOrgNameTagBadRequest) Code() int {
	return 400
}

func (o *DeleteRegistryFunctionOrgNameTagBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagBadRequest) String() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteRegistryFunctionOrgNameTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRegistryFunctionOrgNameTagUnauthorized creates a DeleteRegistryFunctionOrgNameTagUnauthorized with default headers values
func NewDeleteRegistryFunctionOrgNameTagUnauthorized() *DeleteRegistryFunctionOrgNameTagUnauthorized {
	return &DeleteRegistryFunctionOrgNameTagUnauthorized{}
}

/*
DeleteRegistryFunctionOrgNameTagUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteRegistryFunctionOrgNameTagUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this delete registry function org name tag unauthorized response has a 2xx status code
func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete registry function org name tag unauthorized response has a 3xx status code
func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete registry function org name tag unauthorized response has a 4xx status code
func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete registry function org name tag unauthorized response has a 5xx status code
func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete registry function org name tag unauthorized response a status code equal to that given
func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete registry function org name tag unauthorized response
func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) Code() int {
	return 401
}

func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *DeleteRegistryFunctionOrgNameTagUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRegistryFunctionOrgNameTagNotFound creates a DeleteRegistryFunctionOrgNameTagNotFound with default headers values
func NewDeleteRegistryFunctionOrgNameTagNotFound() *DeleteRegistryFunctionOrgNameTagNotFound {
	return &DeleteRegistryFunctionOrgNameTagNotFound{}
}

/*
DeleteRegistryFunctionOrgNameTagNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteRegistryFunctionOrgNameTagNotFound struct {
	Payload string
}

// IsSuccess returns true when this delete registry function org name tag not found response has a 2xx status code
func (o *DeleteRegistryFunctionOrgNameTagNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete registry function org name tag not found response has a 3xx status code
func (o *DeleteRegistryFunctionOrgNameTagNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete registry function org name tag not found response has a 4xx status code
func (o *DeleteRegistryFunctionOrgNameTagNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete registry function org name tag not found response has a 5xx status code
func (o *DeleteRegistryFunctionOrgNameTagNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete registry function org name tag not found response a status code equal to that given
func (o *DeleteRegistryFunctionOrgNameTagNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete registry function org name tag not found response
func (o *DeleteRegistryFunctionOrgNameTagNotFound) Code() int {
	return 404
}

func (o *DeleteRegistryFunctionOrgNameTagNotFound) Error() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagNotFound  %+v", 404, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagNotFound) String() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagNotFound  %+v", 404, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteRegistryFunctionOrgNameTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRegistryFunctionOrgNameTagInternalServerError creates a DeleteRegistryFunctionOrgNameTagInternalServerError with default headers values
func NewDeleteRegistryFunctionOrgNameTagInternalServerError() *DeleteRegistryFunctionOrgNameTagInternalServerError {
	return &DeleteRegistryFunctionOrgNameTagInternalServerError{}
}

/*
DeleteRegistryFunctionOrgNameTagInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteRegistryFunctionOrgNameTagInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this delete registry function org name tag internal server error response has a 2xx status code
func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete registry function org name tag internal server error response has a 3xx status code
func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete registry function org name tag internal server error response has a 4xx status code
func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete registry function org name tag internal server error response has a 5xx status code
func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete registry function org name tag internal server error response a status code equal to that given
func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete registry function org name tag internal server error response
func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) Code() int {
	return 500
}

func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /registry/function/{org}/{name}/{tag}][%d] deleteRegistryFunctionOrgNameTagInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *DeleteRegistryFunctionOrgNameTagInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
