/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// GetRegistrySignatureOrgReader is a Reader for the GetRegistrySignatureOrg structure.
type GetRegistrySignatureOrgReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRegistrySignatureOrgReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRegistrySignatureOrgOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRegistrySignatureOrgBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetRegistrySignatureOrgUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRegistrySignatureOrgNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRegistrySignatureOrgInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /registry/signature/{org}] GetRegistrySignatureOrg", response, response.Code())
	}
}

// NewGetRegistrySignatureOrgOK creates a GetRegistrySignatureOrgOK with default headers values
func NewGetRegistrySignatureOrgOK() *GetRegistrySignatureOrgOK {
	return &GetRegistrySignatureOrgOK{}
}

/*
GetRegistrySignatureOrgOK describes a response with status code 200, with default header values.

OK
*/
type GetRegistrySignatureOrgOK struct {
	Payload []*models.ModelsSignatureResponse
}

// IsSuccess returns true when this get registry signature org o k response has a 2xx status code
func (o *GetRegistrySignatureOrgOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get registry signature org o k response has a 3xx status code
func (o *GetRegistrySignatureOrgOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org o k response has a 4xx status code
func (o *GetRegistrySignatureOrgOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get registry signature org o k response has a 5xx status code
func (o *GetRegistrySignatureOrgOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org o k response a status code equal to that given
func (o *GetRegistrySignatureOrgOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get registry signature org o k response
func (o *GetRegistrySignatureOrgOK) Code() int {
	return 200
}

func (o *GetRegistrySignatureOrgOK) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgOK  %+v", 200, o.Payload)
}

func (o *GetRegistrySignatureOrgOK) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgOK  %+v", 200, o.Payload)
}

func (o *GetRegistrySignatureOrgOK) GetPayload() []*models.ModelsSignatureResponse {
	return o.Payload
}

func (o *GetRegistrySignatureOrgOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgBadRequest creates a GetRegistrySignatureOrgBadRequest with default headers values
func NewGetRegistrySignatureOrgBadRequest() *GetRegistrySignatureOrgBadRequest {
	return &GetRegistrySignatureOrgBadRequest{}
}

/*
GetRegistrySignatureOrgBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetRegistrySignatureOrgBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org bad request response has a 2xx status code
func (o *GetRegistrySignatureOrgBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org bad request response has a 3xx status code
func (o *GetRegistrySignatureOrgBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org bad request response has a 4xx status code
func (o *GetRegistrySignatureOrgBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get registry signature org bad request response has a 5xx status code
func (o *GetRegistrySignatureOrgBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org bad request response a status code equal to that given
func (o *GetRegistrySignatureOrgBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get registry signature org bad request response
func (o *GetRegistrySignatureOrgBadRequest) Code() int {
	return 400
}

func (o *GetRegistrySignatureOrgBadRequest) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgBadRequest  %+v", 400, o.Payload)
}

func (o *GetRegistrySignatureOrgBadRequest) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgBadRequest  %+v", 400, o.Payload)
}

func (o *GetRegistrySignatureOrgBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgUnauthorized creates a GetRegistrySignatureOrgUnauthorized with default headers values
func NewGetRegistrySignatureOrgUnauthorized() *GetRegistrySignatureOrgUnauthorized {
	return &GetRegistrySignatureOrgUnauthorized{}
}

/*
GetRegistrySignatureOrgUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetRegistrySignatureOrgUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org unauthorized response has a 2xx status code
func (o *GetRegistrySignatureOrgUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org unauthorized response has a 3xx status code
func (o *GetRegistrySignatureOrgUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org unauthorized response has a 4xx status code
func (o *GetRegistrySignatureOrgUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get registry signature org unauthorized response has a 5xx status code
func (o *GetRegistrySignatureOrgUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org unauthorized response a status code equal to that given
func (o *GetRegistrySignatureOrgUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get registry signature org unauthorized response
func (o *GetRegistrySignatureOrgUnauthorized) Code() int {
	return 401
}

func (o *GetRegistrySignatureOrgUnauthorized) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgUnauthorized  %+v", 401, o.Payload)
}

func (o *GetRegistrySignatureOrgUnauthorized) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgUnauthorized  %+v", 401, o.Payload)
}

func (o *GetRegistrySignatureOrgUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgNotFound creates a GetRegistrySignatureOrgNotFound with default headers values
func NewGetRegistrySignatureOrgNotFound() *GetRegistrySignatureOrgNotFound {
	return &GetRegistrySignatureOrgNotFound{}
}

/*
GetRegistrySignatureOrgNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetRegistrySignatureOrgNotFound struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org not found response has a 2xx status code
func (o *GetRegistrySignatureOrgNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org not found response has a 3xx status code
func (o *GetRegistrySignatureOrgNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org not found response has a 4xx status code
func (o *GetRegistrySignatureOrgNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get registry signature org not found response has a 5xx status code
func (o *GetRegistrySignatureOrgNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org not found response a status code equal to that given
func (o *GetRegistrySignatureOrgNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get registry signature org not found response
func (o *GetRegistrySignatureOrgNotFound) Code() int {
	return 404
}

func (o *GetRegistrySignatureOrgNotFound) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgNotFound  %+v", 404, o.Payload)
}

func (o *GetRegistrySignatureOrgNotFound) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgNotFound  %+v", 404, o.Payload)
}

func (o *GetRegistrySignatureOrgNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgInternalServerError creates a GetRegistrySignatureOrgInternalServerError with default headers values
func NewGetRegistrySignatureOrgInternalServerError() *GetRegistrySignatureOrgInternalServerError {
	return &GetRegistrySignatureOrgInternalServerError{}
}

/*
GetRegistrySignatureOrgInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetRegistrySignatureOrgInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org internal server error response has a 2xx status code
func (o *GetRegistrySignatureOrgInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org internal server error response has a 3xx status code
func (o *GetRegistrySignatureOrgInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org internal server error response has a 4xx status code
func (o *GetRegistrySignatureOrgInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get registry signature org internal server error response has a 5xx status code
func (o *GetRegistrySignatureOrgInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get registry signature org internal server error response a status code equal to that given
func (o *GetRegistrySignatureOrgInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get registry signature org internal server error response
func (o *GetRegistrySignatureOrgInternalServerError) Code() int {
	return 500
}

func (o *GetRegistrySignatureOrgInternalServerError) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRegistrySignatureOrgInternalServerError) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}][%d] getRegistrySignatureOrgInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRegistrySignatureOrgInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
