/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// GetRegistrySignatureOrgNameTagReader is a Reader for the GetRegistrySignatureOrgNameTag structure.
type GetRegistrySignatureOrgNameTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRegistrySignatureOrgNameTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRegistrySignatureOrgNameTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRegistrySignatureOrgNameTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetRegistrySignatureOrgNameTagUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRegistrySignatureOrgNameTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRegistrySignatureOrgNameTagInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /registry/signature/{org}/{name}/{tag}] GetRegistrySignatureOrgNameTag", response, response.Code())
	}
}

// NewGetRegistrySignatureOrgNameTagOK creates a GetRegistrySignatureOrgNameTagOK with default headers values
func NewGetRegistrySignatureOrgNameTagOK() *GetRegistrySignatureOrgNameTagOK {
	return &GetRegistrySignatureOrgNameTagOK{}
}

/*
GetRegistrySignatureOrgNameTagOK describes a response with status code 200, with default header values.

OK
*/
type GetRegistrySignatureOrgNameTagOK struct {
	Payload *models.ModelsSignatureResponse
}

// IsSuccess returns true when this get registry signature org name tag o k response has a 2xx status code
func (o *GetRegistrySignatureOrgNameTagOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get registry signature org name tag o k response has a 3xx status code
func (o *GetRegistrySignatureOrgNameTagOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org name tag o k response has a 4xx status code
func (o *GetRegistrySignatureOrgNameTagOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get registry signature org name tag o k response has a 5xx status code
func (o *GetRegistrySignatureOrgNameTagOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org name tag o k response a status code equal to that given
func (o *GetRegistrySignatureOrgNameTagOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get registry signature org name tag o k response
func (o *GetRegistrySignatureOrgNameTagOK) Code() int {
	return 200
}

func (o *GetRegistrySignatureOrgNameTagOK) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagOK  %+v", 200, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagOK) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagOK  %+v", 200, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagOK) GetPayload() *models.ModelsSignatureResponse {
	return o.Payload
}

func (o *GetRegistrySignatureOrgNameTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsSignatureResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgNameTagBadRequest creates a GetRegistrySignatureOrgNameTagBadRequest with default headers values
func NewGetRegistrySignatureOrgNameTagBadRequest() *GetRegistrySignatureOrgNameTagBadRequest {
	return &GetRegistrySignatureOrgNameTagBadRequest{}
}

/*
GetRegistrySignatureOrgNameTagBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetRegistrySignatureOrgNameTagBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org name tag bad request response has a 2xx status code
func (o *GetRegistrySignatureOrgNameTagBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org name tag bad request response has a 3xx status code
func (o *GetRegistrySignatureOrgNameTagBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org name tag bad request response has a 4xx status code
func (o *GetRegistrySignatureOrgNameTagBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get registry signature org name tag bad request response has a 5xx status code
func (o *GetRegistrySignatureOrgNameTagBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org name tag bad request response a status code equal to that given
func (o *GetRegistrySignatureOrgNameTagBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get registry signature org name tag bad request response
func (o *GetRegistrySignatureOrgNameTagBadRequest) Code() int {
	return 400
}

func (o *GetRegistrySignatureOrgNameTagBadRequest) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagBadRequest  %+v", 400, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagBadRequest) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagBadRequest  %+v", 400, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgNameTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgNameTagUnauthorized creates a GetRegistrySignatureOrgNameTagUnauthorized with default headers values
func NewGetRegistrySignatureOrgNameTagUnauthorized() *GetRegistrySignatureOrgNameTagUnauthorized {
	return &GetRegistrySignatureOrgNameTagUnauthorized{}
}

/*
GetRegistrySignatureOrgNameTagUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetRegistrySignatureOrgNameTagUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org name tag unauthorized response has a 2xx status code
func (o *GetRegistrySignatureOrgNameTagUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org name tag unauthorized response has a 3xx status code
func (o *GetRegistrySignatureOrgNameTagUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org name tag unauthorized response has a 4xx status code
func (o *GetRegistrySignatureOrgNameTagUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get registry signature org name tag unauthorized response has a 5xx status code
func (o *GetRegistrySignatureOrgNameTagUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org name tag unauthorized response a status code equal to that given
func (o *GetRegistrySignatureOrgNameTagUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get registry signature org name tag unauthorized response
func (o *GetRegistrySignatureOrgNameTagUnauthorized) Code() int {
	return 401
}

func (o *GetRegistrySignatureOrgNameTagUnauthorized) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagUnauthorized  %+v", 401, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagUnauthorized) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagUnauthorized  %+v", 401, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgNameTagUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgNameTagNotFound creates a GetRegistrySignatureOrgNameTagNotFound with default headers values
func NewGetRegistrySignatureOrgNameTagNotFound() *GetRegistrySignatureOrgNameTagNotFound {
	return &GetRegistrySignatureOrgNameTagNotFound{}
}

/*
GetRegistrySignatureOrgNameTagNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetRegistrySignatureOrgNameTagNotFound struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org name tag not found response has a 2xx status code
func (o *GetRegistrySignatureOrgNameTagNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org name tag not found response has a 3xx status code
func (o *GetRegistrySignatureOrgNameTagNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org name tag not found response has a 4xx status code
func (o *GetRegistrySignatureOrgNameTagNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get registry signature org name tag not found response has a 5xx status code
func (o *GetRegistrySignatureOrgNameTagNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get registry signature org name tag not found response a status code equal to that given
func (o *GetRegistrySignatureOrgNameTagNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get registry signature org name tag not found response
func (o *GetRegistrySignatureOrgNameTagNotFound) Code() int {
	return 404
}

func (o *GetRegistrySignatureOrgNameTagNotFound) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagNotFound  %+v", 404, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagNotFound) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagNotFound  %+v", 404, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgNameTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegistrySignatureOrgNameTagInternalServerError creates a GetRegistrySignatureOrgNameTagInternalServerError with default headers values
func NewGetRegistrySignatureOrgNameTagInternalServerError() *GetRegistrySignatureOrgNameTagInternalServerError {
	return &GetRegistrySignatureOrgNameTagInternalServerError{}
}

/*
GetRegistrySignatureOrgNameTagInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetRegistrySignatureOrgNameTagInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get registry signature org name tag internal server error response has a 2xx status code
func (o *GetRegistrySignatureOrgNameTagInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get registry signature org name tag internal server error response has a 3xx status code
func (o *GetRegistrySignatureOrgNameTagInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get registry signature org name tag internal server error response has a 4xx status code
func (o *GetRegistrySignatureOrgNameTagInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get registry signature org name tag internal server error response has a 5xx status code
func (o *GetRegistrySignatureOrgNameTagInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get registry signature org name tag internal server error response a status code equal to that given
func (o *GetRegistrySignatureOrgNameTagInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get registry signature org name tag internal server error response
func (o *GetRegistrySignatureOrgNameTagInternalServerError) Code() int {
	return 500
}

func (o *GetRegistrySignatureOrgNameTagInternalServerError) Error() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagInternalServerError) String() string {
	return fmt.Sprintf("[GET /registry/signature/{org}/{name}/{tag}][%d] getRegistrySignatureOrgNameTagInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRegistrySignatureOrgNameTagInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetRegistrySignatureOrgNameTagInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
