// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsUpdateResponse models update response
//
// swagger:model models.UpdateResponse
type ModelsUpdateResponse struct {

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`
}

// Validate validates this models update response
func (m *ModelsUpdateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models update response based on context it is used
func (m *ModelsUpdateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsUpdateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsUpdateResponse) UnmarshalBinary(b []byte) error {
	var res ModelsUpdateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
