// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsCreateSignatureResponse models create signature response
//
// swagger:model models.CreateSignatureResponse
type ModelsCreateSignatureResponse struct {

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// public
	Public bool `json:"public,omitempty"`

	// published
	Published *ModelsPublishedVersions `json:"published,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this models create signature response
func (m *ModelsCreateSignatureResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePublished(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsCreateSignatureResponse) validatePublished(formats strfmt.Registry) error {
	if swag.IsZero(m.Published) { // not required
		return nil
	}

	if m.Published != nil {
		if err := m.Published.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("published")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("published")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models create signature response based on the context it is used
func (m *ModelsCreateSignatureResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePublished(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsCreateSignatureResponse) contextValidatePublished(ctx context.Context, formats strfmt.Registry) error {

	if m.Published != nil {
		if err := m.Published.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("published")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("published")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsCreateSignatureResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsCreateSignatureResponse) UnmarshalBinary(b []byte) error {
	var res ModelsCreateSignatureResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
