// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsPublishedVersions models published versions
//
// swagger:model models.PublishedVersions
type ModelsPublishedVersions struct {

	// go
	Go *ModelsPublishedVersion `json:"go,omitempty"`
}

// Validate validates this models published versions
func (m *ModelsPublishedVersions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsPublishedVersions) validateGo(formats strfmt.Registry) error {
	if swag.IsZero(m.Go) { // not required
		return nil
	}

	if m.Go != nil {
		if err := m.Go.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("go")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("go")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this models published versions based on the context it is used
func (m *ModelsPublishedVersions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsPublishedVersions) contextValidateGo(ctx context.Context, formats strfmt.Registry) error {

	if m.Go != nil {
		if err := m.Go.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("go")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("go")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsPublishedVersions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsPublishedVersions) UnmarshalBinary(b []byte) error {
	var res ModelsPublishedVersions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
