// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsBuildResponse models build response
//
// swagger:model models.BuildResponse
type ModelsBuildResponse struct {

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`
}

// Validate validates this models build response
func (m *ModelsBuildResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models build response based on context it is used
func (m *ModelsBuildResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsBuildResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsBuildResponse) UnmarshalBinary(b []byte) error {
	var res ModelsBuildResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
