// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SignaturePublishedVersion signature published version
//
// swagger:model signature.PublishedVersion
type SignaturePublishedVersion struct {

	// name
	Name string `json:"name,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this signature published version
func (m *SignaturePublishedVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this signature published version based on context it is used
func (m *SignaturePublishedVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignaturePublishedVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignaturePublishedVersion) UnmarshalBinary(b []byte) error {
	var res SignaturePublishedVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
