before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X "github.com/loopholelabs/scale-cli/version.GitCommit={{.FullCommit}}" -X "github.com/loopholelabs/scale-cli/version.GoVersion={{.Env.GO_VERSION}}" -X "github.com/loopholelabs/scale-cli/version.Platform={{.Env.GO_PLATFORM}}" -X "github.com/loopholelabs/scale-cli/version.Version={{.Tag}}" -X "github.com/loopholelabs/scale-cli/version.BuildDate={{.Env.BUILD_DATE}}" -X "github.com/loopholelabs/scale-cli/analytics/machine.ApplicationID={{.Env.ANALYTICS_APPLICATION_ID}}" -X "github.com/loopholelabs/scale-cli/analytics/posthog.APIKey={{.Env.POSTHOG_API_KEY}}" -X "github.com/loopholelabs/scale-cli/analytics/posthog.APIHost={{.Env.POSTHOG_API_HOST}}"
    main: ./cmd
archives:
  - files:
      - none*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
