before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    ldflags:
      - -s -w -X "github.com/loopholelabs/scale-cli/version.GitCommit={{.FullCommit}}" -X "github.com/loopholelabs/scale-cli/version.GoVersion={{.Env.GO_VERSION}}" -X "github.com/loopholelabs/scale-cli/version.Platform={{.Env.GO_PLATFORM}}" -X "github.com/loopholelabs/scale-cli/version.Version={{.Tag}}" -X "github.com/loopholelabs/scale-cli/version.BuildDate={{.Env.BUILD_DATE}}" -X "github.com/loopholelabs/scale-cli/analytics.AppID={{.Env.ANALYTICS_APP_ID}}" -X "github.com/loopholelabs/scale-cli/analytics.APIKey={{.Env.ANALYTICS_API_KEY}}" -X "github.com/loopholelabs/scale-cli/analytics.APIHost={{.Env.ANALYTICS_API_HOST}}"
    main: ./cmd
archives:
  - files:
      - none*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
release:
  prerelease: "true"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
