/*
	Copyright 2022 Loophole Labs

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		   http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthGithubDeviceParams creates a new GetAuthGithubDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthGithubDeviceParams() *GetAuthGithubDeviceParams {
	return &GetAuthGithubDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthGithubDeviceParamsWithTimeout creates a new GetAuthGithubDeviceParams object
// with the ability to set a timeout on a request.
func NewGetAuthGithubDeviceParamsWithTimeout(timeout time.Duration) *GetAuthGithubDeviceParams {
	return &GetAuthGithubDeviceParams{
		timeout: timeout,
	}
}

// NewGetAuthGithubDeviceParamsWithContext creates a new GetAuthGithubDeviceParams object
// with the ability to set a context for a request.
func NewGetAuthGithubDeviceParamsWithContext(ctx context.Context) *GetAuthGithubDeviceParams {
	return &GetAuthGithubDeviceParams{
		Context: ctx,
	}
}

// NewGetAuthGithubDeviceParamsWithHTTPClient creates a new GetAuthGithubDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthGithubDeviceParamsWithHTTPClient(client *http.Client) *GetAuthGithubDeviceParams {
	return &GetAuthGithubDeviceParams{
		HTTPClient: client,
	}
}

/*
GetAuthGithubDeviceParams contains all the parameters to send to the API endpoint

	for the get auth github device operation.

	Typically these are written to a http.Request.
*/
type GetAuthGithubDeviceParams struct {

	/* DeviceCode.

	   device code
	*/
	DeviceCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth github device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthGithubDeviceParams) WithDefaults() *GetAuthGithubDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth github device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthGithubDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth github device params
func (o *GetAuthGithubDeviceParams) WithTimeout(timeout time.Duration) *GetAuthGithubDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth github device params
func (o *GetAuthGithubDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth github device params
func (o *GetAuthGithubDeviceParams) WithContext(ctx context.Context) *GetAuthGithubDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth github device params
func (o *GetAuthGithubDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth github device params
func (o *GetAuthGithubDeviceParams) WithHTTPClient(client *http.Client) *GetAuthGithubDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth github device params
func (o *GetAuthGithubDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceCode adds the deviceCode to the get auth github device params
func (o *GetAuthGithubDeviceParams) WithDeviceCode(deviceCode string) *GetAuthGithubDeviceParams {
	o.SetDeviceCode(deviceCode)
	return o
}

// SetDeviceCode adds the deviceCode to the get auth github device params
func (o *GetAuthGithubDeviceParams) SetDeviceCode(deviceCode string) {
	o.DeviceCode = deviceCode
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthGithubDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param device_code
	qrDeviceCode := o.DeviceCode
	qDeviceCode := qrDeviceCode
	if qDeviceCode != "" {

		if err := r.SetQueryParam("device_code", qDeviceCode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
