// Code generated by fRPC Go v0.7.0, DO NOT EDIT.
// source: pkg/builder/builder.proto

package builder

import (
	"errors"
	"github.com/loopholelabs/polyglot-go"

	"context"
	"crypto/tls"
	"github.com/loopholelabs/frisbee-go"
	"github.com/loopholelabs/frisbee-go/pkg/packet"
	"github.com/rs/zerolog"

	"sync"
)

var (
	NilDecode = errors.New("cannot decode into a nil root struct")
)

type StreamType uint32

const (
	ERROR  = StreamType(0)
	CLOSE  = StreamType(1)
	STDOUT = StreamType(2)
	STDERR = StreamType(3)
	OUTPUT = StreamType(4)
)

type Dependency struct {
	error error
	flags uint8

	Name    string
	Version string
}

func NewDependency() *Dependency {
	return &Dependency{}
}

func (x *Dependency) Error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *Dependency) Encode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		if x.error != nil {
			polyglot.Encoder(b).Error(x.error)
			return
		}
		polyglot.Encoder(b).Uint8(x.flags)
		polyglot.Encoder(b).String(x.Name).String(x.Version)
	}
}

func (x *Dependency) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *Dependency) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	var err error
	x.error, err = d.Error()
	if err == nil {
		return nil
	}
	x.flags, err = d.Uint8()
	if err != nil {
		return err
	}
	x.Name, err = d.String()
	if err != nil {
		return err
	}
	x.Version, err = d.String()
	if err != nil {
		return err
	}
	return nil
}

type Build struct {
	error error
	flags uint8

	Language     string
	Dependencies []*Dependency
}

func NewBuild() *Build {
	return &Build{}
}

func (x *Build) Error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *Build) Encode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		if x.error != nil {
			polyglot.Encoder(b).Error(x.error)
			return
		}
		polyglot.Encoder(b).Uint8(x.flags)
		polyglot.Encoder(b).String(x.Language)
		polyglot.Encoder(b).Slice(uint32(len(x.Dependencies)), polyglot.AnyKind)
		for _, v := range x.Dependencies {
			v.Encode(b)
		}
	}
}

func (x *Build) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *Build) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	var err error
	x.error, err = d.Error()
	if err == nil {
		return nil
	}
	x.flags, err = d.Uint8()
	if err != nil {
		return err
	}
	x.Language, err = d.String()
	if err != nil {
		return err
	}
	var sliceSize uint32
	sliceSize, err = d.Slice(polyglot.AnyKind)
	if err != nil {
		return err
	}
	if uint32(len(x.Dependencies)) != sliceSize {
		x.Dependencies = make([]*Dependency, sliceSize)
	}
	for i := uint32(0); i < sliceSize; i++ {
		if x.Dependencies[i] == nil {
			x.Dependencies[i] = NewDependency()
		}
		err = x.Dependencies[i].decode(d)
		if err != nil {
			return err
		}
	}
	return nil
}

type ScaleFile struct {
	error error
	flags uint8

	Name  string
	Input []byte
	Build *Build
}

func NewScaleFile() *ScaleFile {
	return &ScaleFile{
		Build: NewBuild(),
	}
}

func (x *ScaleFile) Error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *ScaleFile) Encode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		if x.error != nil {
			polyglot.Encoder(b).Error(x.error)
			return
		}
		polyglot.Encoder(b).Uint8(x.flags)
		polyglot.Encoder(b).String(x.Name).Bytes(x.Input)
		x.Build.Encode(b)
	}
}

func (x *ScaleFile) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *ScaleFile) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	var err error
	x.error, err = d.Error()
	if err == nil {
		return nil
	}
	x.flags, err = d.Uint8()
	if err != nil {
		return err
	}
	x.Name, err = d.String()
	if err != nil {
		return err
	}
	x.Input, err = d.Bytes(nil)
	if err != nil {
		return err
	}
	if x.Build == nil {
		x.Build = NewBuild()
	}
	err = x.Build.decode(d)
	if err != nil {
		return err
	}
	return nil
}

type BuildRequest struct {
	error error
	flags uint8

	Authorization string
	ScaleFile     *ScaleFile
}

func NewBuildRequest() *BuildRequest {
	return &BuildRequest{
		ScaleFile: NewScaleFile(),
	}
}

func (x *BuildRequest) Error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *BuildRequest) Encode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		if x.error != nil {
			polyglot.Encoder(b).Error(x.error)
			return
		}
		polyglot.Encoder(b).Uint8(x.flags)
		polyglot.Encoder(b).String(x.Authorization)
		x.ScaleFile.Encode(b)
	}
}

func (x *BuildRequest) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *BuildRequest) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	var err error
	x.error, err = d.Error()
	if err == nil {
		return nil
	}
	x.flags, err = d.Uint8()
	if err != nil {
		return err
	}
	x.Authorization, err = d.String()
	if err != nil {
		return err
	}
	if x.ScaleFile == nil {
		x.ScaleFile = NewScaleFile()
	}
	err = x.ScaleFile.decode(d)
	if err != nil {
		return err
	}
	return nil
}

type BuildResponse struct {
	error error
	flags uint8

	StreamID uint32
}

func NewBuildResponse() *BuildResponse {
	return &BuildResponse{}
}

func (x *BuildResponse) Error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *BuildResponse) Encode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		if x.error != nil {
			polyglot.Encoder(b).Error(x.error)
			return
		}
		polyglot.Encoder(b).Uint8(x.flags)
		polyglot.Encoder(b).Uint32(x.StreamID)
	}
}

func (x *BuildResponse) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *BuildResponse) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	var err error
	x.error, err = d.Error()
	if err == nil {
		return nil
	}
	x.flags, err = d.Uint8()
	if err != nil {
		return err
	}
	x.StreamID, err = d.Uint32()
	if err != nil {
		return err
	}
	return nil
}

type StreamPacket struct {
	error error
	flags uint8

	Type StreamType
	Data []byte
}

func NewStreamPacket() *StreamPacket {
	return &StreamPacket{}
}

func (x *StreamPacket) Error(b *polyglot.Buffer, err error) {
	polyglot.Encoder(b).Error(err)
}

func (x *StreamPacket) Encode(b *polyglot.Buffer) {
	if x == nil {
		polyglot.Encoder(b).Nil()
	} else {
		if x.error != nil {
			polyglot.Encoder(b).Error(x.error)
			return
		}
		polyglot.Encoder(b).Uint8(x.flags)
		polyglot.Encoder(b).Uint32(uint32(x.Type)).Bytes(x.Data)
	}
}

func (x *StreamPacket) Decode(b []byte) error {
	if x == nil {
		return NilDecode
	}
	d := polyglot.GetDecoder(b)
	defer d.Return()
	return x.decode(d)
}

func (x *StreamPacket) decode(d *polyglot.Decoder) error {
	if d.Nil() {
		return nil
	}

	var err error
	x.error, err = d.Error()
	if err == nil {
		return nil
	}
	x.flags, err = d.Uint8()
	if err != nil {
		return err
	}
	var TypeTemp uint32
	TypeTemp, err = d.Uint32()
	x.Type = StreamType(TypeTemp)
	if err != nil {
		return err
	}
	x.Data, err = d.Bytes(nil)
	if err != nil {
		return err
	}
	return nil
}

type BuildService interface {
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
}

const connectionContextKey int = 1000

func SetCloseFlag(flags uint8, close bool) uint8 {
	return flags | 0x1
}
func HasCloseFlag(flags uint8) bool {
	return flags&1 == 1
}
func SetErrorFlag(flags uint8, error bool) uint8 {
	return flags | 0x2
}
func HasErrorFlag(flags uint8) bool {
	return flags&(1<<1) == 1
}

type ServerMap[T any] struct {
	servers map[uint16]*T
	closed  bool
	mu      sync.Mutex
}

func NewServerMap[T any]() *ServerMap[T] {
	return &ServerMap[T]{servers: make(map[uint16]*T)}
}

type Server struct {
	*frisbee.Server
	onClosed func(*frisbee.Async, error)
}

func NewServer(buildService BuildService, tlsConfig *tls.Config, logger *zerolog.Logger) (*Server, error) {
	var s *Server
	table := make(frisbee.HandlerTable)

	table[10] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		req := NewBuildRequest()
		err := req.Decode((*incoming.Content)[:incoming.Metadata.ContentLength])
		if err == nil {
			var res *BuildResponse
			outgoing = incoming
			outgoing.Content.Reset()
			res, err = buildService.Build(ctx, req)
			if err != nil {
				if _, ok := err.(CloseError); ok {
					action = frisbee.CLOSE
				}
				res.Error(outgoing.Content, err)
			} else {
				res.Encode(outgoing.Content)
			}
			outgoing.Metadata.ContentLength = uint32(len(*outgoing.Content))
		}
		return
	}
	var fsrv *frisbee.Server
	var err error
	if tlsConfig != nil {
		fsrv, err = frisbee.NewServer(table, frisbee.WithTLS(tlsConfig), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	} else {
		fsrv, err = frisbee.NewServer(table, frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	}

	fsrv.ConnContext = func(ctx context.Context, conn *frisbee.Async) context.Context {
		return context.WithValue(ctx, connectionContextKey, conn)
	}
	s, err = &Server{
		Server: fsrv,
	}, nil

	fsrv.SetOnClosed(func(async *frisbee.Async, err error) {
		if s.onClosed != nil {
			s.onClosed(async, err)
		}
	})

	return s, err
}

func (s *Server) SetOnClosed(f func(*frisbee.Async, error)) error {
	if f == nil {
		return frisbee.OnClosedNil
	}
	s.onClosed = f
	return nil
}

type subBuildServiceClient struct {
	client          *frisbee.Client
	nextBuild       uint16
	nextBuildMu     sync.RWMutex
	inflightBuild   map[uint16]chan *BuildResponse
	inflightBuildMu sync.RWMutex
}
type Client struct {
	*frisbee.Client
	BuildService *subBuildServiceClient
}

func NewClient(tlsConfig *tls.Config, logger *zerolog.Logger) (*Client, error) {
	c := new(Client)
	table := make(frisbee.HandlerTable)

	table[10] = func(ctx context.Context, incoming *packet.Packet) (outgoing *packet.Packet, action frisbee.Action) {
		c.BuildService.inflightBuildMu.RLock()
		if ch, ok := c.BuildService.inflightBuild[incoming.Metadata.Id]; ok {
			c.BuildService.inflightBuildMu.RUnlock()
			res := NewBuildResponse()
			res.Decode((*incoming.Content)[:incoming.Metadata.ContentLength])
			ch <- res
		} else {
			c.BuildService.inflightBuildMu.RUnlock()
		}
		return
	}
	var err error
	if tlsConfig != nil {
		c.Client, err = frisbee.NewClient(table, context.Background(), frisbee.WithTLS(tlsConfig), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	} else {
		c.Client, err = frisbee.NewClient(table, context.Background(), frisbee.WithLogger(logger))
		if err != nil {
			return nil, err
		}
	}

	c.BuildService = new(subBuildServiceClient)
	c.BuildService.client = c.Client
	c.BuildService.nextBuildMu.Lock()
	c.BuildService.nextBuild = 0
	c.BuildService.nextBuildMu.Unlock()
	c.BuildService.inflightBuild = make(map[uint16]chan *BuildResponse)
	return c, nil
}

func (c *subBuildServiceClient) Build(ctx context.Context, req *BuildRequest) (res *BuildResponse, err error) {
	ch := make(chan *BuildResponse, 1)
	p := packet.Get()
	p.Metadata.Operation = 10

	c.nextBuildMu.Lock()
	c.nextBuild += 1
	id := c.nextBuild
	c.nextBuildMu.Unlock()
	p.Metadata.Id = id

	req.Encode(p.Content)
	p.Metadata.ContentLength = uint32(len(*p.Content))
	c.inflightBuildMu.Lock()
	c.inflightBuild[id] = ch
	c.inflightBuildMu.Unlock()
	err = c.client.WritePacket(p)
	if err != nil {
		packet.Put(p)
		return
	}
	select {
	case res = <-ch:
		err = res.error
	case <-ctx.Done():
		err = ctx.Err()
	}
	c.inflightBuildMu.Lock()
	delete(c.inflightBuild, id)
	c.inflightBuildMu.Unlock()
	packet.Put(p)
	return
}

type CloseError struct {
	err error
}

func NewCloseError(err error) CloseError {
	return CloseError{err: err}
}

func (e CloseError) Error() string {
	return e.err.Error()
}
