// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/pkg/api/client/models"
)

// PostAuthRefreshReader is a Reader for the PostAuthRefresh structure.
type PostAuthRefreshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthRefreshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthRefreshOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthRefreshBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAuthRefreshUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthRefreshInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAuthRefreshOK creates a PostAuthRefreshOK with default headers values
func NewPostAuthRefreshOK() *PostAuthRefreshOK {
	return &PostAuthRefreshOK{}
}

/* PostAuthRefreshOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthRefreshOK struct {
	Payload *models.ModelsRefreshResponse
}

// IsSuccess returns true when this post auth refresh o k response has a 2xx status code
func (o *PostAuthRefreshOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth refresh o k response has a 3xx status code
func (o *PostAuthRefreshOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth refresh o k response has a 4xx status code
func (o *PostAuthRefreshOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth refresh o k response has a 5xx status code
func (o *PostAuthRefreshOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth refresh o k response a status code equal to that given
func (o *PostAuthRefreshOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostAuthRefreshOK) Error() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshOK  %+v", 200, o.Payload)
}

func (o *PostAuthRefreshOK) String() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshOK  %+v", 200, o.Payload)
}

func (o *PostAuthRefreshOK) GetPayload() *models.ModelsRefreshResponse {
	return o.Payload
}

func (o *PostAuthRefreshOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsRefreshResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthRefreshBadRequest creates a PostAuthRefreshBadRequest with default headers values
func NewPostAuthRefreshBadRequest() *PostAuthRefreshBadRequest {
	return &PostAuthRefreshBadRequest{}
}

/* PostAuthRefreshBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAuthRefreshBadRequest struct {
	Payload *models.ModelsRefreshError
}

// IsSuccess returns true when this post auth refresh bad request response has a 2xx status code
func (o *PostAuthRefreshBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth refresh bad request response has a 3xx status code
func (o *PostAuthRefreshBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth refresh bad request response has a 4xx status code
func (o *PostAuthRefreshBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth refresh bad request response has a 5xx status code
func (o *PostAuthRefreshBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth refresh bad request response a status code equal to that given
func (o *PostAuthRefreshBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *PostAuthRefreshBadRequest) Error() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshBadRequest  %+v", 400, o.Payload)
}

func (o *PostAuthRefreshBadRequest) String() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshBadRequest  %+v", 400, o.Payload)
}

func (o *PostAuthRefreshBadRequest) GetPayload() *models.ModelsRefreshError {
	return o.Payload
}

func (o *PostAuthRefreshBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsRefreshError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthRefreshUnauthorized creates a PostAuthRefreshUnauthorized with default headers values
func NewPostAuthRefreshUnauthorized() *PostAuthRefreshUnauthorized {
	return &PostAuthRefreshUnauthorized{}
}

/* PostAuthRefreshUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAuthRefreshUnauthorized struct {
	Payload *models.ModelsRefreshError
}

// IsSuccess returns true when this post auth refresh unauthorized response has a 2xx status code
func (o *PostAuthRefreshUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth refresh unauthorized response has a 3xx status code
func (o *PostAuthRefreshUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth refresh unauthorized response has a 4xx status code
func (o *PostAuthRefreshUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth refresh unauthorized response has a 5xx status code
func (o *PostAuthRefreshUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth refresh unauthorized response a status code equal to that given
func (o *PostAuthRefreshUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *PostAuthRefreshUnauthorized) Error() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAuthRefreshUnauthorized) String() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAuthRefreshUnauthorized) GetPayload() *models.ModelsRefreshError {
	return o.Payload
}

func (o *PostAuthRefreshUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsRefreshError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthRefreshInternalServerError creates a PostAuthRefreshInternalServerError with default headers values
func NewPostAuthRefreshInternalServerError() *PostAuthRefreshInternalServerError {
	return &PostAuthRefreshInternalServerError{}
}

/* PostAuthRefreshInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAuthRefreshInternalServerError struct {
	Payload *models.ModelsRefreshError
}

// IsSuccess returns true when this post auth refresh internal server error response has a 2xx status code
func (o *PostAuthRefreshInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth refresh internal server error response has a 3xx status code
func (o *PostAuthRefreshInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth refresh internal server error response has a 4xx status code
func (o *PostAuthRefreshInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth refresh internal server error response has a 5xx status code
func (o *PostAuthRefreshInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post auth refresh internal server error response a status code equal to that given
func (o *PostAuthRefreshInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *PostAuthRefreshInternalServerError) Error() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAuthRefreshInternalServerError) String() string {
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAuthRefreshInternalServerError) GetPayload() *models.ModelsRefreshError {
	return o.Payload
}

func (o *PostAuthRefreshInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsRefreshError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
