// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRegistrySignatureNameVersionParams creates a new GetRegistrySignatureNameVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRegistrySignatureNameVersionParams() *GetRegistrySignatureNameVersionParams {
	return &GetRegistrySignatureNameVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegistrySignatureNameVersionParamsWithTimeout creates a new GetRegistrySignatureNameVersionParams object
// with the ability to set a timeout on a request.
func NewGetRegistrySignatureNameVersionParamsWithTimeout(timeout time.Duration) *GetRegistrySignatureNameVersionParams {
	return &GetRegistrySignatureNameVersionParams{
		timeout: timeout,
	}
}

// NewGetRegistrySignatureNameVersionParamsWithContext creates a new GetRegistrySignatureNameVersionParams object
// with the ability to set a context for a request.
func NewGetRegistrySignatureNameVersionParamsWithContext(ctx context.Context) *GetRegistrySignatureNameVersionParams {
	return &GetRegistrySignatureNameVersionParams{
		Context: ctx,
	}
}

// NewGetRegistrySignatureNameVersionParamsWithHTTPClient creates a new GetRegistrySignatureNameVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRegistrySignatureNameVersionParamsWithHTTPClient(client *http.Client) *GetRegistrySignatureNameVersionParams {
	return &GetRegistrySignatureNameVersionParams{
		HTTPClient: client,
	}
}

/*
GetRegistrySignatureNameVersionParams contains all the parameters to send to the API endpoint

	for the get registry signature name version operation.

	Typically these are written to a http.Request.
*/
type GetRegistrySignatureNameVersionParams struct {

	/* Name.

	   name
	*/
	Name string

	/* Version.

	   version
	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get registry signature name version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRegistrySignatureNameVersionParams) WithDefaults() *GetRegistrySignatureNameVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get registry signature name version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRegistrySignatureNameVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) WithTimeout(timeout time.Duration) *GetRegistrySignatureNameVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) WithContext(ctx context.Context) *GetRegistrySignatureNameVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) WithHTTPClient(client *http.Client) *GetRegistrySignatureNameVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) WithName(name string) *GetRegistrySignatureNameVersionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) SetName(name string) {
	o.Name = name
}

// WithVersion adds the version to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) WithVersion(version string) *GetRegistrySignatureNameVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get registry signature name version params
func (o *GetRegistrySignatureNameVersionParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistrySignatureNameVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
