// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new registry API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for registry API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetRegistrySignatureNamespaceNameVersion(params *GetRegistrySignatureNamespaceNameVersionParams, opts ...ClientOption) (*GetRegistrySignatureNamespaceNameVersionOK, error)

	PostRegistrySignature(params *PostRegistrySignatureParams, opts ...ClientOption) (*PostRegistrySignatureOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetRegistrySignatureNamespaceNameVersion gets signature retrieves a public signature

GetSignature retrieves a public signature
*/
func (a *Client) GetRegistrySignatureNamespaceNameVersion(params *GetRegistrySignatureNamespaceNameVersionParams, opts ...ClientOption) (*GetRegistrySignatureNamespaceNameVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRegistrySignatureNamespaceNameVersionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetRegistrySignatureNamespaceNameVersion",
		Method:             "GET",
		PathPattern:        "/registry/signature/{namespace}/{name}/{version}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRegistrySignatureNamespaceNameVersionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRegistrySignatureNamespaceNameVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetRegistrySignatureNamespaceNameVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostRegistrySignature creates signature creates a new signature in the user s namespace

CreateSignature creates a new signature in the user's namespace
*/
func (a *Client) PostRegistrySignature(params *PostRegistrySignatureParams, opts ...ClientOption) (*PostRegistrySignatureOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostRegistrySignatureParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostRegistrySignature",
		Method:             "POST",
		PathPattern:        "/registry/signature",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostRegistrySignatureReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostRegistrySignatureOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostRegistrySignature: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
