// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new config API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for config API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetConfigAuth(params *GetConfigAuthParams, opts ...ClientOption) (*GetConfigAuthOK, error)

	GetConfigBuild(params *GetConfigBuildParams, opts ...ClientOption) (*GetConfigBuildOK, error)

	GetConfigUpdate(params *GetConfigUpdateParams, opts ...ClientOption) (*GetConfigUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetConfigAuth retrieves the authentication configuration

Retrieve the Authentication Configuration
*/
func (a *Client) GetConfigAuth(params *GetConfigAuthParams, opts ...ClientOption) (*GetConfigAuthOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConfigAuthParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetConfigAuth",
		Method:             "GET",
		PathPattern:        "/config/auth",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetConfigAuthReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConfigAuthOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetConfigAuth: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetConfigBuild retrieves the build configuration

Retrieve the Build Configuration
*/
func (a *Client) GetConfigBuild(params *GetConfigBuildParams, opts ...ClientOption) (*GetConfigBuildOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConfigBuildParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetConfigBuild",
		Method:             "GET",
		PathPattern:        "/config/build",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetConfigBuildReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConfigBuildOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetConfigBuild: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetConfigUpdate retrieves the update configuration

Retrieve the Update Configuration
*/
func (a *Client) GetConfigUpdate(params *GetConfigUpdateParams, opts ...ClientOption) (*GetConfigUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConfigUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetConfigUpdate",
		Method:             "GET",
		PathPattern:        "/config/update",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetConfigUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConfigUpdateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetConfigUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
