// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/pkg/client/models"
)

// GetConfigUpdateReader is a Reader for the GetConfigUpdate structure.
type GetConfigUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetConfigUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetConfigUpdateOK creates a GetConfigUpdateOK with default headers values
func NewGetConfigUpdateOK() *GetConfigUpdateOK {
	return &GetConfigUpdateOK{}
}

/*
	GetConfigUpdateOK describes a response with status code 200, with default header values.

OK
*/
type GetConfigUpdateOK struct {
	Payload *models.ModelsUpdateResponse
}

// IsSuccess returns true when this get config update o k response has a 2xx status code
func (o *GetConfigUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get config update o k response has a 3xx status code
func (o *GetConfigUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get config update o k response has a 4xx status code
func (o *GetConfigUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get config update o k response has a 5xx status code
func (o *GetConfigUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get config update o k response a status code equal to that given
func (o *GetConfigUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetConfigUpdateOK) Error() string {
	return fmt.Sprintf("[GET /config/update][%d] getConfigUpdateOK  %+v", 200, o.Payload)
}

func (o *GetConfigUpdateOK) String() string {
	return fmt.Sprintf("[GET /config/update][%d] getConfigUpdateOK  %+v", 200, o.Payload)
}

func (o *GetConfigUpdateOK) GetPayload() *models.ModelsUpdateResponse {
	return o.Payload
}

func (o *GetConfigUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsUpdateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigUpdateInternalServerError creates a GetConfigUpdateInternalServerError with default headers values
func NewGetConfigUpdateInternalServerError() *GetConfigUpdateInternalServerError {
	return &GetConfigUpdateInternalServerError{}
}

/*
	GetConfigUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetConfigUpdateInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get config update internal server error response has a 2xx status code
func (o *GetConfigUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get config update internal server error response has a 3xx status code
func (o *GetConfigUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get config update internal server error response has a 4xx status code
func (o *GetConfigUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get config update internal server error response has a 5xx status code
func (o *GetConfigUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get config update internal server error response a status code equal to that given
func (o *GetConfigUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetConfigUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /config/update][%d] getConfigUpdateInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfigUpdateInternalServerError) String() string {
	return fmt.Sprintf("[GET /config/update][%d] getConfigUpdateInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfigUpdateInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetConfigUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
