// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/pkg/client/models"
)

// GetConfigAuthReader is a Reader for the GetConfigAuth structure.
type GetConfigAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetConfigAuthInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetConfigAuthOK creates a GetConfigAuthOK with default headers values
func NewGetConfigAuthOK() *GetConfigAuthOK {
	return &GetConfigAuthOK{}
}

/*
	GetConfigAuthOK describes a response with status code 200, with default header values.

OK
*/
type GetConfigAuthOK struct {
	Payload *models.ModelsAuthResponse
}

// IsSuccess returns true when this get config auth o k response has a 2xx status code
func (o *GetConfigAuthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get config auth o k response has a 3xx status code
func (o *GetConfigAuthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get config auth o k response has a 4xx status code
func (o *GetConfigAuthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get config auth o k response has a 5xx status code
func (o *GetConfigAuthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get config auth o k response a status code equal to that given
func (o *GetConfigAuthOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetConfigAuthOK) Error() string {
	return fmt.Sprintf("[GET /config/auth][%d] getConfigAuthOK  %+v", 200, o.Payload)
}

func (o *GetConfigAuthOK) String() string {
	return fmt.Sprintf("[GET /config/auth][%d] getConfigAuthOK  %+v", 200, o.Payload)
}

func (o *GetConfigAuthOK) GetPayload() *models.ModelsAuthResponse {
	return o.Payload
}

func (o *GetConfigAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsAuthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigAuthInternalServerError creates a GetConfigAuthInternalServerError with default headers values
func NewGetConfigAuthInternalServerError() *GetConfigAuthInternalServerError {
	return &GetConfigAuthInternalServerError{}
}

/*
	GetConfigAuthInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetConfigAuthInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get config auth internal server error response has a 2xx status code
func (o *GetConfigAuthInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get config auth internal server error response has a 3xx status code
func (o *GetConfigAuthInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get config auth internal server error response has a 4xx status code
func (o *GetConfigAuthInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get config auth internal server error response has a 5xx status code
func (o *GetConfigAuthInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get config auth internal server error response a status code equal to that given
func (o *GetConfigAuthInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetConfigAuthInternalServerError) Error() string {
	return fmt.Sprintf("[GET /config/auth][%d] getConfigAuthInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfigAuthInternalServerError) String() string {
	return fmt.Sprintf("[GET /config/auth][%d] getConfigAuthInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfigAuthInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetConfigAuthInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
