// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConfigUpdateParams creates a new GetConfigUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetConfigUpdateParams() *GetConfigUpdateParams {
	return &GetConfigUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetConfigUpdateParamsWithTimeout creates a new GetConfigUpdateParams object
// with the ability to set a timeout on a request.
func NewGetConfigUpdateParamsWithTimeout(timeout time.Duration) *GetConfigUpdateParams {
	return &GetConfigUpdateParams{
		timeout: timeout,
	}
}

// NewGetConfigUpdateParamsWithContext creates a new GetConfigUpdateParams object
// with the ability to set a context for a request.
func NewGetConfigUpdateParamsWithContext(ctx context.Context) *GetConfigUpdateParams {
	return &GetConfigUpdateParams{
		Context: ctx,
	}
}

// NewGetConfigUpdateParamsWithHTTPClient creates a new GetConfigUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetConfigUpdateParamsWithHTTPClient(client *http.Client) *GetConfigUpdateParams {
	return &GetConfigUpdateParams{
		HTTPClient: client,
	}
}

/*
GetConfigUpdateParams contains all the parameters to send to the API endpoint

	for the get config update operation.

	Typically these are written to a http.Request.
*/
type GetConfigUpdateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get config update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConfigUpdateParams) WithDefaults() *GetConfigUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get config update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConfigUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get config update params
func (o *GetConfigUpdateParams) WithTimeout(timeout time.Duration) *GetConfigUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get config update params
func (o *GetConfigUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get config update params
func (o *GetConfigUpdateParams) WithContext(ctx context.Context) *GetConfigUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get config update params
func (o *GetConfigUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get config update params
func (o *GetConfigUpdateParams) WithHTTPClient(client *http.Client) *GetConfigUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get config update params
func (o *GetConfigUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetConfigUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
