name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
          cache: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          install-only: true

      - id: build-variables
        run: |
          echo "go-version=$(go version | cut -d' ' -f3)" >> $GITHUB_OUTPUT
          echo "go-platform=$(go version | cut -d' ' -f4)" >> $GITHUB_OUTPUT
          echo "build-date=$(date)" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        run: goreleaser release --rm-dist
        env:
          GO_VERSION: ${{ steps.build-variables.outputs.go-version }}
          GO_PLATFORM: ${{ steps.build-variables.outputs.go-platform }}
          BUILD_DATE: ${{ steps.build-variables.outputs.build-date }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
