name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          install-only: true

      - id: build-variables
        run: |
          echo "::set-output name=go-version::$(go version | cut -d' ' -f3)"
          echo "::set-output name=go-platform::$(go version | cut -d' ' -f4)"

      - name: Run GoReleaser
        run: goreleaser release --rm-dist
        env:
          GO_VERSION: ${{ steps.build-variables.outputs.go-version }}
          GO_PLATFORM: ${{ steps.build-variables.outputs.go-platform }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
