name: Release

on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - id: build-variables
        run: |
          echo "go-version=$(go version | cut -d' ' -f3)" >> $GITHUB_OUTPUT
          echo "go-platform=$(go version | cut -d' ' -f4)" >> $GITHUB_OUTPUT
          echo "build-date=$(date)" >> $GITHUB_OUTPUT

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GO_VERSION: ${{ steps.build-variables.outputs.go-version }}
          GO_PLATFORM: ${{ steps.build-variables.outputs.go-platform }}
          BUILD_DATE: ${{ steps.build-variables.outputs.build-date }}
          ANALYTICS_APP_ID: ${{ secrets.ANALYTICS_APP_ID }}
          ANALYTICS_API_KEY: ${{ secrets.ANALYTICS_API_KEY }}
          ANALYTICS_API_HOST: ${{ secrets.ANALYTICS_API_HOST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}