/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAccessOrganizationNameParams creates a new DeleteAccessOrganizationNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAccessOrganizationNameParams() *DeleteAccessOrganizationNameParams {
	return &DeleteAccessOrganizationNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAccessOrganizationNameParamsWithTimeout creates a new DeleteAccessOrganizationNameParams object
// with the ability to set a timeout on a request.
func NewDeleteAccessOrganizationNameParamsWithTimeout(timeout time.Duration) *DeleteAccessOrganizationNameParams {
	return &DeleteAccessOrganizationNameParams{
		timeout: timeout,
	}
}

// NewDeleteAccessOrganizationNameParamsWithContext creates a new DeleteAccessOrganizationNameParams object
// with the ability to set a context for a request.
func NewDeleteAccessOrganizationNameParamsWithContext(ctx context.Context) *DeleteAccessOrganizationNameParams {
	return &DeleteAccessOrganizationNameParams{
		Context: ctx,
	}
}

// NewDeleteAccessOrganizationNameParamsWithHTTPClient creates a new DeleteAccessOrganizationNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAccessOrganizationNameParamsWithHTTPClient(client *http.Client) *DeleteAccessOrganizationNameParams {
	return &DeleteAccessOrganizationNameParams{
		HTTPClient: client,
	}
}

/*
DeleteAccessOrganizationNameParams contains all the parameters to send to the API endpoint

	for the delete access organization name operation.

	Typically these are written to a http.Request.
*/
type DeleteAccessOrganizationNameParams struct {

	/* Name.

	   Organization Name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete access organization name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAccessOrganizationNameParams) WithDefaults() *DeleteAccessOrganizationNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete access organization name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAccessOrganizationNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) WithTimeout(timeout time.Duration) *DeleteAccessOrganizationNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) WithContext(ctx context.Context) *DeleteAccessOrganizationNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) WithHTTPClient(client *http.Client) *DeleteAccessOrganizationNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) WithName(name string) *DeleteAccessOrganizationNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete access organization name params
func (o *DeleteAccessOrganizationNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAccessOrganizationNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
