/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAccessOrganizationInviteEmailParams creates a new DeleteAccessOrganizationInviteEmailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAccessOrganizationInviteEmailParams() *DeleteAccessOrganizationInviteEmailParams {
	return &DeleteAccessOrganizationInviteEmailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAccessOrganizationInviteEmailParamsWithTimeout creates a new DeleteAccessOrganizationInviteEmailParams object
// with the ability to set a timeout on a request.
func NewDeleteAccessOrganizationInviteEmailParamsWithTimeout(timeout time.Duration) *DeleteAccessOrganizationInviteEmailParams {
	return &DeleteAccessOrganizationInviteEmailParams{
		timeout: timeout,
	}
}

// NewDeleteAccessOrganizationInviteEmailParamsWithContext creates a new DeleteAccessOrganizationInviteEmailParams object
// with the ability to set a context for a request.
func NewDeleteAccessOrganizationInviteEmailParamsWithContext(ctx context.Context) *DeleteAccessOrganizationInviteEmailParams {
	return &DeleteAccessOrganizationInviteEmailParams{
		Context: ctx,
	}
}

// NewDeleteAccessOrganizationInviteEmailParamsWithHTTPClient creates a new DeleteAccessOrganizationInviteEmailParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAccessOrganizationInviteEmailParamsWithHTTPClient(client *http.Client) *DeleteAccessOrganizationInviteEmailParams {
	return &DeleteAccessOrganizationInviteEmailParams{
		HTTPClient: client,
	}
}

/*
DeleteAccessOrganizationInviteEmailParams contains all the parameters to send to the API endpoint

	for the delete access organization invite email operation.

	Typically these are written to a http.Request.
*/
type DeleteAccessOrganizationInviteEmailParams struct {

	/* Email.

	   Organization Invite Email
	*/
	Email string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete access organization invite email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAccessOrganizationInviteEmailParams) WithDefaults() *DeleteAccessOrganizationInviteEmailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete access organization invite email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAccessOrganizationInviteEmailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) WithTimeout(timeout time.Duration) *DeleteAccessOrganizationInviteEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) WithContext(ctx context.Context) *DeleteAccessOrganizationInviteEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) WithHTTPClient(client *http.Client) *DeleteAccessOrganizationInviteEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) WithEmail(email string) *DeleteAccessOrganizationInviteEmailParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the delete access organization invite email params
func (o *DeleteAccessOrganizationInviteEmailParams) SetEmail(email string) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAccessOrganizationInviteEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param email
	if err := r.SetPathParam("email", o.Email); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
