/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAccessOrganizationInviteEmailReader is a Reader for the DeleteAccessOrganizationInviteEmail structure.
type DeleteAccessOrganizationInviteEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccessOrganizationInviteEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAccessOrganizationInviteEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAccessOrganizationInviteEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAccessOrganizationInviteEmailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAccessOrganizationInviteEmailInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteAccessOrganizationInviteEmailNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /access/organization/invite/{email}] DeleteAccessOrganizationInviteEmail", response, response.Code())
	}
}

// NewDeleteAccessOrganizationInviteEmailOK creates a DeleteAccessOrganizationInviteEmailOK with default headers values
func NewDeleteAccessOrganizationInviteEmailOK() *DeleteAccessOrganizationInviteEmailOK {
	return &DeleteAccessOrganizationInviteEmailOK{}
}

/*
DeleteAccessOrganizationInviteEmailOK describes a response with status code 200, with default header values.

OK
*/
type DeleteAccessOrganizationInviteEmailOK struct {
	Payload string
}

// IsSuccess returns true when this delete access organization invite email o k response has a 2xx status code
func (o *DeleteAccessOrganizationInviteEmailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete access organization invite email o k response has a 3xx status code
func (o *DeleteAccessOrganizationInviteEmailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization invite email o k response has a 4xx status code
func (o *DeleteAccessOrganizationInviteEmailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access organization invite email o k response has a 5xx status code
func (o *DeleteAccessOrganizationInviteEmailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access organization invite email o k response a status code equal to that given
func (o *DeleteAccessOrganizationInviteEmailOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete access organization invite email o k response
func (o *DeleteAccessOrganizationInviteEmailOK) Code() int {
	return 200
}

func (o *DeleteAccessOrganizationInviteEmailOK) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailOK  %+v", 200, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailOK) String() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailOK  %+v", 200, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationInviteEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationInviteEmailUnauthorized creates a DeleteAccessOrganizationInviteEmailUnauthorized with default headers values
func NewDeleteAccessOrganizationInviteEmailUnauthorized() *DeleteAccessOrganizationInviteEmailUnauthorized {
	return &DeleteAccessOrganizationInviteEmailUnauthorized{}
}

/*
DeleteAccessOrganizationInviteEmailUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteAccessOrganizationInviteEmailUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this delete access organization invite email unauthorized response has a 2xx status code
func (o *DeleteAccessOrganizationInviteEmailUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization invite email unauthorized response has a 3xx status code
func (o *DeleteAccessOrganizationInviteEmailUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization invite email unauthorized response has a 4xx status code
func (o *DeleteAccessOrganizationInviteEmailUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete access organization invite email unauthorized response has a 5xx status code
func (o *DeleteAccessOrganizationInviteEmailUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access organization invite email unauthorized response a status code equal to that given
func (o *DeleteAccessOrganizationInviteEmailUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete access organization invite email unauthorized response
func (o *DeleteAccessOrganizationInviteEmailUnauthorized) Code() int {
	return 401
}

func (o *DeleteAccessOrganizationInviteEmailUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationInviteEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationInviteEmailNotFound creates a DeleteAccessOrganizationInviteEmailNotFound with default headers values
func NewDeleteAccessOrganizationInviteEmailNotFound() *DeleteAccessOrganizationInviteEmailNotFound {
	return &DeleteAccessOrganizationInviteEmailNotFound{}
}

/*
DeleteAccessOrganizationInviteEmailNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAccessOrganizationInviteEmailNotFound struct {
	Payload string
}

// IsSuccess returns true when this delete access organization invite email not found response has a 2xx status code
func (o *DeleteAccessOrganizationInviteEmailNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization invite email not found response has a 3xx status code
func (o *DeleteAccessOrganizationInviteEmailNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization invite email not found response has a 4xx status code
func (o *DeleteAccessOrganizationInviteEmailNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete access organization invite email not found response has a 5xx status code
func (o *DeleteAccessOrganizationInviteEmailNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access organization invite email not found response a status code equal to that given
func (o *DeleteAccessOrganizationInviteEmailNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete access organization invite email not found response
func (o *DeleteAccessOrganizationInviteEmailNotFound) Code() int {
	return 404
}

func (o *DeleteAccessOrganizationInviteEmailNotFound) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailNotFound) String() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationInviteEmailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationInviteEmailInternalServerError creates a DeleteAccessOrganizationInviteEmailInternalServerError with default headers values
func NewDeleteAccessOrganizationInviteEmailInternalServerError() *DeleteAccessOrganizationInviteEmailInternalServerError {
	return &DeleteAccessOrganizationInviteEmailInternalServerError{}
}

/*
DeleteAccessOrganizationInviteEmailInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteAccessOrganizationInviteEmailInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this delete access organization invite email internal server error response has a 2xx status code
func (o *DeleteAccessOrganizationInviteEmailInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization invite email internal server error response has a 3xx status code
func (o *DeleteAccessOrganizationInviteEmailInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization invite email internal server error response has a 4xx status code
func (o *DeleteAccessOrganizationInviteEmailInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access organization invite email internal server error response has a 5xx status code
func (o *DeleteAccessOrganizationInviteEmailInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete access organization invite email internal server error response a status code equal to that given
func (o *DeleteAccessOrganizationInviteEmailInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete access organization invite email internal server error response
func (o *DeleteAccessOrganizationInviteEmailInternalServerError) Code() int {
	return 500
}

func (o *DeleteAccessOrganizationInviteEmailInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationInviteEmailInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationInviteEmailNotImplemented creates a DeleteAccessOrganizationInviteEmailNotImplemented with default headers values
func NewDeleteAccessOrganizationInviteEmailNotImplemented() *DeleteAccessOrganizationInviteEmailNotImplemented {
	return &DeleteAccessOrganizationInviteEmailNotImplemented{}
}

/*
DeleteAccessOrganizationInviteEmailNotImplemented describes a response with status code 501, with default header values.

Not Implemented
*/
type DeleteAccessOrganizationInviteEmailNotImplemented struct {
	Payload string
}

// IsSuccess returns true when this delete access organization invite email not implemented response has a 2xx status code
func (o *DeleteAccessOrganizationInviteEmailNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization invite email not implemented response has a 3xx status code
func (o *DeleteAccessOrganizationInviteEmailNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization invite email not implemented response has a 4xx status code
func (o *DeleteAccessOrganizationInviteEmailNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access organization invite email not implemented response has a 5xx status code
func (o *DeleteAccessOrganizationInviteEmailNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this delete access organization invite email not implemented response a status code equal to that given
func (o *DeleteAccessOrganizationInviteEmailNotImplemented) IsCode(code int) bool {
	return code == 501
}

// Code gets the status code for the delete access organization invite email not implemented response
func (o *DeleteAccessOrganizationInviteEmailNotImplemented) Code() int {
	return 501
}

func (o *DeleteAccessOrganizationInviteEmailNotImplemented) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailNotImplemented) String() string {
	return fmt.Sprintf("[DELETE /access/organization/invite/{email}][%d] deleteAccessOrganizationInviteEmailNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteAccessOrganizationInviteEmailNotImplemented) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationInviteEmailNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
