/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAccessOrganizationNameReader is a Reader for the DeleteAccessOrganizationName structure.
type DeleteAccessOrganizationNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccessOrganizationNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAccessOrganizationNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAccessOrganizationNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAccessOrganizationNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAccessOrganizationNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteAccessOrganizationNameNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /access/organization/{name}] DeleteAccessOrganizationName", response, response.Code())
	}
}

// NewDeleteAccessOrganizationNameOK creates a DeleteAccessOrganizationNameOK with default headers values
func NewDeleteAccessOrganizationNameOK() *DeleteAccessOrganizationNameOK {
	return &DeleteAccessOrganizationNameOK{}
}

/*
DeleteAccessOrganizationNameOK describes a response with status code 200, with default header values.

OK
*/
type DeleteAccessOrganizationNameOK struct {
	Payload string
}

// IsSuccess returns true when this delete access organization name o k response has a 2xx status code
func (o *DeleteAccessOrganizationNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete access organization name o k response has a 3xx status code
func (o *DeleteAccessOrganizationNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization name o k response has a 4xx status code
func (o *DeleteAccessOrganizationNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access organization name o k response has a 5xx status code
func (o *DeleteAccessOrganizationNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access organization name o k response a status code equal to that given
func (o *DeleteAccessOrganizationNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete access organization name o k response
func (o *DeleteAccessOrganizationNameOK) Code() int {
	return 200
}

func (o *DeleteAccessOrganizationNameOK) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameOK  %+v", 200, o.Payload)
}

func (o *DeleteAccessOrganizationNameOK) String() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameOK  %+v", 200, o.Payload)
}

func (o *DeleteAccessOrganizationNameOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationNameUnauthorized creates a DeleteAccessOrganizationNameUnauthorized with default headers values
func NewDeleteAccessOrganizationNameUnauthorized() *DeleteAccessOrganizationNameUnauthorized {
	return &DeleteAccessOrganizationNameUnauthorized{}
}

/*
DeleteAccessOrganizationNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteAccessOrganizationNameUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this delete access organization name unauthorized response has a 2xx status code
func (o *DeleteAccessOrganizationNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization name unauthorized response has a 3xx status code
func (o *DeleteAccessOrganizationNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization name unauthorized response has a 4xx status code
func (o *DeleteAccessOrganizationNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete access organization name unauthorized response has a 5xx status code
func (o *DeleteAccessOrganizationNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access organization name unauthorized response a status code equal to that given
func (o *DeleteAccessOrganizationNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete access organization name unauthorized response
func (o *DeleteAccessOrganizationNameUnauthorized) Code() int {
	return 401
}

func (o *DeleteAccessOrganizationNameUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAccessOrganizationNameUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAccessOrganizationNameUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationNameNotFound creates a DeleteAccessOrganizationNameNotFound with default headers values
func NewDeleteAccessOrganizationNameNotFound() *DeleteAccessOrganizationNameNotFound {
	return &DeleteAccessOrganizationNameNotFound{}
}

/*
DeleteAccessOrganizationNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAccessOrganizationNameNotFound struct {
	Payload string
}

// IsSuccess returns true when this delete access organization name not found response has a 2xx status code
func (o *DeleteAccessOrganizationNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization name not found response has a 3xx status code
func (o *DeleteAccessOrganizationNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization name not found response has a 4xx status code
func (o *DeleteAccessOrganizationNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete access organization name not found response has a 5xx status code
func (o *DeleteAccessOrganizationNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access organization name not found response a status code equal to that given
func (o *DeleteAccessOrganizationNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete access organization name not found response
func (o *DeleteAccessOrganizationNameNotFound) Code() int {
	return 404
}

func (o *DeleteAccessOrganizationNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccessOrganizationNameNotFound) String() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccessOrganizationNameNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationNameInternalServerError creates a DeleteAccessOrganizationNameInternalServerError with default headers values
func NewDeleteAccessOrganizationNameInternalServerError() *DeleteAccessOrganizationNameInternalServerError {
	return &DeleteAccessOrganizationNameInternalServerError{}
}

/*
DeleteAccessOrganizationNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteAccessOrganizationNameInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this delete access organization name internal server error response has a 2xx status code
func (o *DeleteAccessOrganizationNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization name internal server error response has a 3xx status code
func (o *DeleteAccessOrganizationNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization name internal server error response has a 4xx status code
func (o *DeleteAccessOrganizationNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access organization name internal server error response has a 5xx status code
func (o *DeleteAccessOrganizationNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete access organization name internal server error response a status code equal to that given
func (o *DeleteAccessOrganizationNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete access organization name internal server error response
func (o *DeleteAccessOrganizationNameInternalServerError) Code() int {
	return 500
}

func (o *DeleteAccessOrganizationNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteAccessOrganizationNameInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteAccessOrganizationNameInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessOrganizationNameNotImplemented creates a DeleteAccessOrganizationNameNotImplemented with default headers values
func NewDeleteAccessOrganizationNameNotImplemented() *DeleteAccessOrganizationNameNotImplemented {
	return &DeleteAccessOrganizationNameNotImplemented{}
}

/*
DeleteAccessOrganizationNameNotImplemented describes a response with status code 501, with default header values.

Not Implemented
*/
type DeleteAccessOrganizationNameNotImplemented struct {
	Payload string
}

// IsSuccess returns true when this delete access organization name not implemented response has a 2xx status code
func (o *DeleteAccessOrganizationNameNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access organization name not implemented response has a 3xx status code
func (o *DeleteAccessOrganizationNameNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access organization name not implemented response has a 4xx status code
func (o *DeleteAccessOrganizationNameNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access organization name not implemented response has a 5xx status code
func (o *DeleteAccessOrganizationNameNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this delete access organization name not implemented response a status code equal to that given
func (o *DeleteAccessOrganizationNameNotImplemented) IsCode(code int) bool {
	return code == 501
}

// Code gets the status code for the delete access organization name not implemented response
func (o *DeleteAccessOrganizationNameNotImplemented) Code() int {
	return 501
}

func (o *DeleteAccessOrganizationNameNotImplemented) Error() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteAccessOrganizationNameNotImplemented) String() string {
	return fmt.Sprintf("[DELETE /access/organization/{name}][%d] deleteAccessOrganizationNameNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteAccessOrganizationNameNotImplemented) GetPayload() string {
	return o.Payload
}

func (o *DeleteAccessOrganizationNameNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
