/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// GetAccessOrganizationInviteReader is a Reader for the GetAccessOrganizationInvite structure.
type GetAccessOrganizationInviteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccessOrganizationInviteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccessOrganizationInviteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAccessOrganizationInviteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAccessOrganizationInviteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /access/organization/invite] GetAccessOrganizationInvite", response, response.Code())
	}
}

// NewGetAccessOrganizationInviteOK creates a GetAccessOrganizationInviteOK with default headers values
func NewGetAccessOrganizationInviteOK() *GetAccessOrganizationInviteOK {
	return &GetAccessOrganizationInviteOK{}
}

/*
GetAccessOrganizationInviteOK describes a response with status code 200, with default header values.

OK
*/
type GetAccessOrganizationInviteOK struct {
	Payload []*models.ModelsOrganizationResponse
}

// IsSuccess returns true when this get access organization invite o k response has a 2xx status code
func (o *GetAccessOrganizationInviteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get access organization invite o k response has a 3xx status code
func (o *GetAccessOrganizationInviteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get access organization invite o k response has a 4xx status code
func (o *GetAccessOrganizationInviteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get access organization invite o k response has a 5xx status code
func (o *GetAccessOrganizationInviteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get access organization invite o k response a status code equal to that given
func (o *GetAccessOrganizationInviteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get access organization invite o k response
func (o *GetAccessOrganizationInviteOK) Code() int {
	return 200
}

func (o *GetAccessOrganizationInviteOK) Error() string {
	return fmt.Sprintf("[GET /access/organization/invite][%d] getAccessOrganizationInviteOK  %+v", 200, o.Payload)
}

func (o *GetAccessOrganizationInviteOK) String() string {
	return fmt.Sprintf("[GET /access/organization/invite][%d] getAccessOrganizationInviteOK  %+v", 200, o.Payload)
}

func (o *GetAccessOrganizationInviteOK) GetPayload() []*models.ModelsOrganizationResponse {
	return o.Payload
}

func (o *GetAccessOrganizationInviteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccessOrganizationInviteUnauthorized creates a GetAccessOrganizationInviteUnauthorized with default headers values
func NewGetAccessOrganizationInviteUnauthorized() *GetAccessOrganizationInviteUnauthorized {
	return &GetAccessOrganizationInviteUnauthorized{}
}

/*
GetAccessOrganizationInviteUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAccessOrganizationInviteUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get access organization invite unauthorized response has a 2xx status code
func (o *GetAccessOrganizationInviteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get access organization invite unauthorized response has a 3xx status code
func (o *GetAccessOrganizationInviteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get access organization invite unauthorized response has a 4xx status code
func (o *GetAccessOrganizationInviteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get access organization invite unauthorized response has a 5xx status code
func (o *GetAccessOrganizationInviteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get access organization invite unauthorized response a status code equal to that given
func (o *GetAccessOrganizationInviteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get access organization invite unauthorized response
func (o *GetAccessOrganizationInviteUnauthorized) Code() int {
	return 401
}

func (o *GetAccessOrganizationInviteUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access/organization/invite][%d] getAccessOrganizationInviteUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAccessOrganizationInviteUnauthorized) String() string {
	return fmt.Sprintf("[GET /access/organization/invite][%d] getAccessOrganizationInviteUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAccessOrganizationInviteUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetAccessOrganizationInviteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccessOrganizationInviteInternalServerError creates a GetAccessOrganizationInviteInternalServerError with default headers values
func NewGetAccessOrganizationInviteInternalServerError() *GetAccessOrganizationInviteInternalServerError {
	return &GetAccessOrganizationInviteInternalServerError{}
}

/*
GetAccessOrganizationInviteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAccessOrganizationInviteInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get access organization invite internal server error response has a 2xx status code
func (o *GetAccessOrganizationInviteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get access organization invite internal server error response has a 3xx status code
func (o *GetAccessOrganizationInviteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get access organization invite internal server error response has a 4xx status code
func (o *GetAccessOrganizationInviteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get access organization invite internal server error response has a 5xx status code
func (o *GetAccessOrganizationInviteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get access organization invite internal server error response a status code equal to that given
func (o *GetAccessOrganizationInviteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get access organization invite internal server error response
func (o *GetAccessOrganizationInviteInternalServerError) Code() int {
	return 500
}

func (o *GetAccessOrganizationInviteInternalServerError) Error() string {
	return fmt.Sprintf("[GET /access/organization/invite][%d] getAccessOrganizationInviteInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAccessOrganizationInviteInternalServerError) String() string {
	return fmt.Sprintf("[GET /access/organization/invite][%d] getAccessOrganizationInviteInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAccessOrganizationInviteInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetAccessOrganizationInviteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
