/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccessInviteParams creates a new GetAccessInviteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccessInviteParams() *GetAccessInviteParams {
	return &GetAccessInviteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccessInviteParamsWithTimeout creates a new GetAccessInviteParams object
// with the ability to set a timeout on a request.
func NewGetAccessInviteParamsWithTimeout(timeout time.Duration) *GetAccessInviteParams {
	return &GetAccessInviteParams{
		timeout: timeout,
	}
}

// NewGetAccessInviteParamsWithContext creates a new GetAccessInviteParams object
// with the ability to set a context for a request.
func NewGetAccessInviteParamsWithContext(ctx context.Context) *GetAccessInviteParams {
	return &GetAccessInviteParams{
		Context: ctx,
	}
}

// NewGetAccessInviteParamsWithHTTPClient creates a new GetAccessInviteParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccessInviteParamsWithHTTPClient(client *http.Client) *GetAccessInviteParams {
	return &GetAccessInviteParams{
		HTTPClient: client,
	}
}

/*
GetAccessInviteParams contains all the parameters to send to the API endpoint

	for the get access invite operation.

	Typically these are written to a http.Request.
*/
type GetAccessInviteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get access invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccessInviteParams) WithDefaults() *GetAccessInviteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get access invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccessInviteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get access invite params
func (o *GetAccessInviteParams) WithTimeout(timeout time.Duration) *GetAccessInviteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get access invite params
func (o *GetAccessInviteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get access invite params
func (o *GetAccessInviteParams) WithContext(ctx context.Context) *GetAccessInviteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get access invite params
func (o *GetAccessInviteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get access invite params
func (o *GetAccessInviteParams) WithHTTPClient(client *http.Client) *GetAccessInviteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get access invite params
func (o *GetAccessInviteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccessInviteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
