/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// GetAccessOrganizationReader is a Reader for the GetAccessOrganization structure.
type GetAccessOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccessOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccessOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAccessOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAccessOrganizationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /access/organization] GetAccessOrganization", response, response.Code())
	}
}

// NewGetAccessOrganizationOK creates a GetAccessOrganizationOK with default headers values
func NewGetAccessOrganizationOK() *GetAccessOrganizationOK {
	return &GetAccessOrganizationOK{}
}

/*
GetAccessOrganizationOK describes a response with status code 200, with default header values.

OK
*/
type GetAccessOrganizationOK struct {
	Payload []*models.ModelsOrganizationResponse
}

// IsSuccess returns true when this get access organization o k response has a 2xx status code
func (o *GetAccessOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get access organization o k response has a 3xx status code
func (o *GetAccessOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get access organization o k response has a 4xx status code
func (o *GetAccessOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get access organization o k response has a 5xx status code
func (o *GetAccessOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get access organization o k response a status code equal to that given
func (o *GetAccessOrganizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get access organization o k response
func (o *GetAccessOrganizationOK) Code() int {
	return 200
}

func (o *GetAccessOrganizationOK) Error() string {
	return fmt.Sprintf("[GET /access/organization][%d] getAccessOrganizationOK  %+v", 200, o.Payload)
}

func (o *GetAccessOrganizationOK) String() string {
	return fmt.Sprintf("[GET /access/organization][%d] getAccessOrganizationOK  %+v", 200, o.Payload)
}

func (o *GetAccessOrganizationOK) GetPayload() []*models.ModelsOrganizationResponse {
	return o.Payload
}

func (o *GetAccessOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccessOrganizationUnauthorized creates a GetAccessOrganizationUnauthorized with default headers values
func NewGetAccessOrganizationUnauthorized() *GetAccessOrganizationUnauthorized {
	return &GetAccessOrganizationUnauthorized{}
}

/*
GetAccessOrganizationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAccessOrganizationUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get access organization unauthorized response has a 2xx status code
func (o *GetAccessOrganizationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get access organization unauthorized response has a 3xx status code
func (o *GetAccessOrganizationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get access organization unauthorized response has a 4xx status code
func (o *GetAccessOrganizationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get access organization unauthorized response has a 5xx status code
func (o *GetAccessOrganizationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get access organization unauthorized response a status code equal to that given
func (o *GetAccessOrganizationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get access organization unauthorized response
func (o *GetAccessOrganizationUnauthorized) Code() int {
	return 401
}

func (o *GetAccessOrganizationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access/organization][%d] getAccessOrganizationUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAccessOrganizationUnauthorized) String() string {
	return fmt.Sprintf("[GET /access/organization][%d] getAccessOrganizationUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAccessOrganizationUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetAccessOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccessOrganizationInternalServerError creates a GetAccessOrganizationInternalServerError with default headers values
func NewGetAccessOrganizationInternalServerError() *GetAccessOrganizationInternalServerError {
	return &GetAccessOrganizationInternalServerError{}
}

/*
GetAccessOrganizationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAccessOrganizationInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get access organization internal server error response has a 2xx status code
func (o *GetAccessOrganizationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get access organization internal server error response has a 3xx status code
func (o *GetAccessOrganizationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get access organization internal server error response has a 4xx status code
func (o *GetAccessOrganizationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get access organization internal server error response has a 5xx status code
func (o *GetAccessOrganizationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get access organization internal server error response a status code equal to that given
func (o *GetAccessOrganizationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get access organization internal server error response
func (o *GetAccessOrganizationInternalServerError) Code() int {
	return 500
}

func (o *GetAccessOrganizationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /access/organization][%d] getAccessOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAccessOrganizationInternalServerError) String() string {
	return fmt.Sprintf("[GET /access/organization][%d] getAccessOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAccessOrganizationInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetAccessOrganizationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
