/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAccessInviteOrganizationParams creates a new PostAccessInviteOrganizationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAccessInviteOrganizationParams() *PostAccessInviteOrganizationParams {
	return &PostAccessInviteOrganizationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccessInviteOrganizationParamsWithTimeout creates a new PostAccessInviteOrganizationParams object
// with the ability to set a timeout on a request.
func NewPostAccessInviteOrganizationParamsWithTimeout(timeout time.Duration) *PostAccessInviteOrganizationParams {
	return &PostAccessInviteOrganizationParams{
		timeout: timeout,
	}
}

// NewPostAccessInviteOrganizationParamsWithContext creates a new PostAccessInviteOrganizationParams object
// with the ability to set a context for a request.
func NewPostAccessInviteOrganizationParamsWithContext(ctx context.Context) *PostAccessInviteOrganizationParams {
	return &PostAccessInviteOrganizationParams{
		Context: ctx,
	}
}

// NewPostAccessInviteOrganizationParamsWithHTTPClient creates a new PostAccessInviteOrganizationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAccessInviteOrganizationParamsWithHTTPClient(client *http.Client) *PostAccessInviteOrganizationParams {
	return &PostAccessInviteOrganizationParams{
		HTTPClient: client,
	}
}

/*
PostAccessInviteOrganizationParams contains all the parameters to send to the API endpoint

	for the post access invite organization operation.

	Typically these are written to a http.Request.
*/
type PostAccessInviteOrganizationParams struct {

	/* Organization.

	   Organization Name
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post access invite organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessInviteOrganizationParams) WithDefaults() *PostAccessInviteOrganizationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post access invite organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessInviteOrganizationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) WithTimeout(timeout time.Duration) *PostAccessInviteOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) WithContext(ctx context.Context) *PostAccessInviteOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) WithHTTPClient(client *http.Client) *PostAccessInviteOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) WithOrganization(organization string) *PostAccessInviteOrganizationParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post access invite organization params
func (o *PostAccessInviteOrganizationParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccessInviteOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
