/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// PostAccessOrganizationInviteReader is a Reader for the PostAccessOrganizationInvite structure.
type PostAccessOrganizationInviteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAccessOrganizationInviteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAccessOrganizationInviteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAccessOrganizationInviteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAccessOrganizationInviteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAccessOrganizationInviteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /access/organization/invite] PostAccessOrganizationInvite", response, response.Code())
	}
}

// NewPostAccessOrganizationInviteOK creates a PostAccessOrganizationInviteOK with default headers values
func NewPostAccessOrganizationInviteOK() *PostAccessOrganizationInviteOK {
	return &PostAccessOrganizationInviteOK{}
}

/*
PostAccessOrganizationInviteOK describes a response with status code 200, with default header values.

OK
*/
type PostAccessOrganizationInviteOK struct {
	Payload *models.ModelsOrganizationInviteResponse
}

// IsSuccess returns true when this post access organization invite o k response has a 2xx status code
func (o *PostAccessOrganizationInviteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post access organization invite o k response has a 3xx status code
func (o *PostAccessOrganizationInviteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization invite o k response has a 4xx status code
func (o *PostAccessOrganizationInviteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post access organization invite o k response has a 5xx status code
func (o *PostAccessOrganizationInviteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post access organization invite o k response a status code equal to that given
func (o *PostAccessOrganizationInviteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post access organization invite o k response
func (o *PostAccessOrganizationInviteOK) Code() int {
	return 200
}

func (o *PostAccessOrganizationInviteOK) Error() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteOK  %+v", 200, o.Payload)
}

func (o *PostAccessOrganizationInviteOK) String() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteOK  %+v", 200, o.Payload)
}

func (o *PostAccessOrganizationInviteOK) GetPayload() *models.ModelsOrganizationInviteResponse {
	return o.Payload
}

func (o *PostAccessOrganizationInviteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOrganizationInviteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAccessOrganizationInviteBadRequest creates a PostAccessOrganizationInviteBadRequest with default headers values
func NewPostAccessOrganizationInviteBadRequest() *PostAccessOrganizationInviteBadRequest {
	return &PostAccessOrganizationInviteBadRequest{}
}

/*
PostAccessOrganizationInviteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAccessOrganizationInviteBadRequest struct {
	Payload string
}

// IsSuccess returns true when this post access organization invite bad request response has a 2xx status code
func (o *PostAccessOrganizationInviteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post access organization invite bad request response has a 3xx status code
func (o *PostAccessOrganizationInviteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization invite bad request response has a 4xx status code
func (o *PostAccessOrganizationInviteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post access organization invite bad request response has a 5xx status code
func (o *PostAccessOrganizationInviteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post access organization invite bad request response a status code equal to that given
func (o *PostAccessOrganizationInviteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post access organization invite bad request response
func (o *PostAccessOrganizationInviteBadRequest) Code() int {
	return 400
}

func (o *PostAccessOrganizationInviteBadRequest) Error() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteBadRequest  %+v", 400, o.Payload)
}

func (o *PostAccessOrganizationInviteBadRequest) String() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteBadRequest  %+v", 400, o.Payload)
}

func (o *PostAccessOrganizationInviteBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PostAccessOrganizationInviteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAccessOrganizationInviteUnauthorized creates a PostAccessOrganizationInviteUnauthorized with default headers values
func NewPostAccessOrganizationInviteUnauthorized() *PostAccessOrganizationInviteUnauthorized {
	return &PostAccessOrganizationInviteUnauthorized{}
}

/*
PostAccessOrganizationInviteUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAccessOrganizationInviteUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this post access organization invite unauthorized response has a 2xx status code
func (o *PostAccessOrganizationInviteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post access organization invite unauthorized response has a 3xx status code
func (o *PostAccessOrganizationInviteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization invite unauthorized response has a 4xx status code
func (o *PostAccessOrganizationInviteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post access organization invite unauthorized response has a 5xx status code
func (o *PostAccessOrganizationInviteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post access organization invite unauthorized response a status code equal to that given
func (o *PostAccessOrganizationInviteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post access organization invite unauthorized response
func (o *PostAccessOrganizationInviteUnauthorized) Code() int {
	return 401
}

func (o *PostAccessOrganizationInviteUnauthorized) Error() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAccessOrganizationInviteUnauthorized) String() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAccessOrganizationInviteUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *PostAccessOrganizationInviteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAccessOrganizationInviteInternalServerError creates a PostAccessOrganizationInviteInternalServerError with default headers values
func NewPostAccessOrganizationInviteInternalServerError() *PostAccessOrganizationInviteInternalServerError {
	return &PostAccessOrganizationInviteInternalServerError{}
}

/*
PostAccessOrganizationInviteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAccessOrganizationInviteInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this post access organization invite internal server error response has a 2xx status code
func (o *PostAccessOrganizationInviteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post access organization invite internal server error response has a 3xx status code
func (o *PostAccessOrganizationInviteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization invite internal server error response has a 4xx status code
func (o *PostAccessOrganizationInviteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post access organization invite internal server error response has a 5xx status code
func (o *PostAccessOrganizationInviteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post access organization invite internal server error response a status code equal to that given
func (o *PostAccessOrganizationInviteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post access organization invite internal server error response
func (o *PostAccessOrganizationInviteInternalServerError) Code() int {
	return 500
}

func (o *PostAccessOrganizationInviteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAccessOrganizationInviteInternalServerError) String() string {
	return fmt.Sprintf("[POST /access/organization/invite][%d] postAccessOrganizationInviteInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAccessOrganizationInviteInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostAccessOrganizationInviteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
