/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// NewPostAccessOrganizationInviteParams creates a new PostAccessOrganizationInviteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAccessOrganizationInviteParams() *PostAccessOrganizationInviteParams {
	return &PostAccessOrganizationInviteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccessOrganizationInviteParamsWithTimeout creates a new PostAccessOrganizationInviteParams object
// with the ability to set a timeout on a request.
func NewPostAccessOrganizationInviteParamsWithTimeout(timeout time.Duration) *PostAccessOrganizationInviteParams {
	return &PostAccessOrganizationInviteParams{
		timeout: timeout,
	}
}

// NewPostAccessOrganizationInviteParamsWithContext creates a new PostAccessOrganizationInviteParams object
// with the ability to set a context for a request.
func NewPostAccessOrganizationInviteParamsWithContext(ctx context.Context) *PostAccessOrganizationInviteParams {
	return &PostAccessOrganizationInviteParams{
		Context: ctx,
	}
}

// NewPostAccessOrganizationInviteParamsWithHTTPClient creates a new PostAccessOrganizationInviteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAccessOrganizationInviteParamsWithHTTPClient(client *http.Client) *PostAccessOrganizationInviteParams {
	return &PostAccessOrganizationInviteParams{
		HTTPClient: client,
	}
}

/*
PostAccessOrganizationInviteParams contains all the parameters to send to the API endpoint

	for the post access organization invite operation.

	Typically these are written to a http.Request.
*/
type PostAccessOrganizationInviteParams struct {

	/* Request.

	   Create Invite Request
	*/
	Request *models.ModelsCreateOrganizationInviteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post access organization invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessOrganizationInviteParams) WithDefaults() *PostAccessOrganizationInviteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post access organization invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessOrganizationInviteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) WithTimeout(timeout time.Duration) *PostAccessOrganizationInviteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) WithContext(ctx context.Context) *PostAccessOrganizationInviteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) WithHTTPClient(client *http.Client) *PostAccessOrganizationInviteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) WithRequest(request *models.ModelsCreateOrganizationInviteRequest) *PostAccessOrganizationInviteParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post access organization invite params
func (o *PostAccessOrganizationInviteParams) SetRequest(request *models.ModelsCreateOrganizationInviteRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccessOrganizationInviteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
