/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// NewPostAccessOrganizationParams creates a new PostAccessOrganizationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAccessOrganizationParams() *PostAccessOrganizationParams {
	return &PostAccessOrganizationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccessOrganizationParamsWithTimeout creates a new PostAccessOrganizationParams object
// with the ability to set a timeout on a request.
func NewPostAccessOrganizationParamsWithTimeout(timeout time.Duration) *PostAccessOrganizationParams {
	return &PostAccessOrganizationParams{
		timeout: timeout,
	}
}

// NewPostAccessOrganizationParamsWithContext creates a new PostAccessOrganizationParams object
// with the ability to set a context for a request.
func NewPostAccessOrganizationParamsWithContext(ctx context.Context) *PostAccessOrganizationParams {
	return &PostAccessOrganizationParams{
		Context: ctx,
	}
}

// NewPostAccessOrganizationParamsWithHTTPClient creates a new PostAccessOrganizationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAccessOrganizationParamsWithHTTPClient(client *http.Client) *PostAccessOrganizationParams {
	return &PostAccessOrganizationParams{
		HTTPClient: client,
	}
}

/*
PostAccessOrganizationParams contains all the parameters to send to the API endpoint

	for the post access organization operation.

	Typically these are written to a http.Request.
*/
type PostAccessOrganizationParams struct {

	/* Request.

	   Create Organization Request
	*/
	Request *models.ModelsCreateOrganizationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post access organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessOrganizationParams) WithDefaults() *PostAccessOrganizationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post access organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAccessOrganizationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post access organization params
func (o *PostAccessOrganizationParams) WithTimeout(timeout time.Duration) *PostAccessOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post access organization params
func (o *PostAccessOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post access organization params
func (o *PostAccessOrganizationParams) WithContext(ctx context.Context) *PostAccessOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post access organization params
func (o *PostAccessOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post access organization params
func (o *PostAccessOrganizationParams) WithHTTPClient(client *http.Client) *PostAccessOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post access organization params
func (o *PostAccessOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post access organization params
func (o *PostAccessOrganizationParams) WithRequest(request *models.ModelsCreateOrganizationRequest) *PostAccessOrganizationParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post access organization params
func (o *PostAccessOrganizationParams) SetRequest(request *models.ModelsCreateOrganizationRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccessOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
