/*
 	Copyright 2023 Loophole Labs

 	Licensed under the Apache License, Version 2.0 (the "License");
 	you may not use this file except in compliance with the License.
 	You may obtain a copy of the License at

 		   http://www.apache.org/licenses/LICENSE-2.0

 	Unless required by applicable law or agreed to in writing, software
 	distributed under the License is distributed on an "AS IS" BASIS,
 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	See the License for the specific language governing permissions and
 	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/scale-cli/client/models"
)

// PostAccessOrganizationReader is a Reader for the PostAccessOrganization structure.
type PostAccessOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAccessOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAccessOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAccessOrganizationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAccessOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAccessOrganizationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /access/organization] PostAccessOrganization", response, response.Code())
	}
}

// NewPostAccessOrganizationOK creates a PostAccessOrganizationOK with default headers values
func NewPostAccessOrganizationOK() *PostAccessOrganizationOK {
	return &PostAccessOrganizationOK{}
}

/*
PostAccessOrganizationOK describes a response with status code 200, with default header values.

OK
*/
type PostAccessOrganizationOK struct {
	Payload *models.ModelsOrganizationResponse
}

// IsSuccess returns true when this post access organization o k response has a 2xx status code
func (o *PostAccessOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post access organization o k response has a 3xx status code
func (o *PostAccessOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization o k response has a 4xx status code
func (o *PostAccessOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post access organization o k response has a 5xx status code
func (o *PostAccessOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post access organization o k response a status code equal to that given
func (o *PostAccessOrganizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post access organization o k response
func (o *PostAccessOrganizationOK) Code() int {
	return 200
}

func (o *PostAccessOrganizationOK) Error() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationOK  %+v", 200, o.Payload)
}

func (o *PostAccessOrganizationOK) String() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationOK  %+v", 200, o.Payload)
}

func (o *PostAccessOrganizationOK) GetPayload() *models.ModelsOrganizationResponse {
	return o.Payload
}

func (o *PostAccessOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOrganizationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAccessOrganizationBadRequest creates a PostAccessOrganizationBadRequest with default headers values
func NewPostAccessOrganizationBadRequest() *PostAccessOrganizationBadRequest {
	return &PostAccessOrganizationBadRequest{}
}

/*
PostAccessOrganizationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAccessOrganizationBadRequest struct {
	Payload string
}

// IsSuccess returns true when this post access organization bad request response has a 2xx status code
func (o *PostAccessOrganizationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post access organization bad request response has a 3xx status code
func (o *PostAccessOrganizationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization bad request response has a 4xx status code
func (o *PostAccessOrganizationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post access organization bad request response has a 5xx status code
func (o *PostAccessOrganizationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post access organization bad request response a status code equal to that given
func (o *PostAccessOrganizationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post access organization bad request response
func (o *PostAccessOrganizationBadRequest) Code() int {
	return 400
}

func (o *PostAccessOrganizationBadRequest) Error() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationBadRequest  %+v", 400, o.Payload)
}

func (o *PostAccessOrganizationBadRequest) String() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationBadRequest  %+v", 400, o.Payload)
}

func (o *PostAccessOrganizationBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PostAccessOrganizationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAccessOrganizationUnauthorized creates a PostAccessOrganizationUnauthorized with default headers values
func NewPostAccessOrganizationUnauthorized() *PostAccessOrganizationUnauthorized {
	return &PostAccessOrganizationUnauthorized{}
}

/*
PostAccessOrganizationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAccessOrganizationUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this post access organization unauthorized response has a 2xx status code
func (o *PostAccessOrganizationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post access organization unauthorized response has a 3xx status code
func (o *PostAccessOrganizationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization unauthorized response has a 4xx status code
func (o *PostAccessOrganizationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post access organization unauthorized response has a 5xx status code
func (o *PostAccessOrganizationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post access organization unauthorized response a status code equal to that given
func (o *PostAccessOrganizationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post access organization unauthorized response
func (o *PostAccessOrganizationUnauthorized) Code() int {
	return 401
}

func (o *PostAccessOrganizationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAccessOrganizationUnauthorized) String() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAccessOrganizationUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *PostAccessOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAccessOrganizationInternalServerError creates a PostAccessOrganizationInternalServerError with default headers values
func NewPostAccessOrganizationInternalServerError() *PostAccessOrganizationInternalServerError {
	return &PostAccessOrganizationInternalServerError{}
}

/*
PostAccessOrganizationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAccessOrganizationInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this post access organization internal server error response has a 2xx status code
func (o *PostAccessOrganizationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post access organization internal server error response has a 3xx status code
func (o *PostAccessOrganizationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post access organization internal server error response has a 4xx status code
func (o *PostAccessOrganizationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post access organization internal server error response has a 5xx status code
func (o *PostAccessOrganizationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post access organization internal server error response a status code equal to that given
func (o *PostAccessOrganizationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post access organization internal server error response
func (o *PostAccessOrganizationInternalServerError) Code() int {
	return 500
}

func (o *PostAccessOrganizationInternalServerError) Error() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAccessOrganizationInternalServerError) String() string {
	return fmt.Sprintf("[POST /access/organization][%d] postAccessOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAccessOrganizationInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostAccessOrganizationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
